server:
  port: 9099
spring:
  application:
    name: user-api
  datasource:
    url: jdbc:postgresql://localhost:5432/user_api
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
